import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/images/chatbottest.png" width={620} height={500} />
            <p>
              Chatbot helps people in a way that a reader can easily understand
              the topic by querying the keywords that were fetched from the
              newspaper or article.
            </p>
            <button
              onClick={() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LmCCSKVLUoxwByRBYgwN5Tp",
                      quantity: 1,
                    },
                  ],
                });
              }}
            >
              Buy the project
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
